apps/clinica/urls.py
from django.urls import path
from .views import crearPaciente, crearConsulta, listarPaciente, editarPaciente

urlpatterns=[
    path('crear_paciente/', crearPaciente ,name= 'crear_paciente'),
    path('crear_consulta/', crearConsulta ,name= 'crear_consulta'),
    path('listar_paciente/',listarPaciente, name = 'listar_paciente'),
    path('editar_paciente/<int:expediente>',editarPaciente, name = 'editar_paciente'),
    
]

sismedica/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.clinica.views import Home
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinica/',include(('apps.clinica.urls','clinica'))),
    path('home/',Home, name = 'index'),
    path('', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/',LogoutView.as_view(next_page='login'),name='logout')
]

apps/clinica/models.py
from django.db import models

# Create your models here.


class Paciente(models.Model):
    id_paciente = models.AutoField(primary_key=True)
    expediente = models.IntegerField('No.Expediente',blank=False, null=False)
    nombre = models.CharField('Nombre',max_length=100, blank=False, null=False)
    apellidos = models.CharField('Apellidos', max_length=100, blank=False, null=False)
    dui = models.CharField('DUI', max_length=10, blank=False,null=False)
    sexo = models.CharField('Sexo', max_length=1, blank=False, null=False)
    email = models.CharField('email',max_length=100,blank=False, null=False)
    estadoCivil = models.CharField('estadoCivil', max_length=10, blank=False,null=False)
    telefono = models.CharField('Telefono', max_length=9, blank=False,null=False)
    fechaNaci = models.DateField('Fecha de Nacimiento',blank=False,null=False)
    direccion = models.TextField('Direccion',max_length=300, blank=False,null=False)
    departamento = models.CharField('Departamento',max_length=100,blank=False,null=False)
    municipio = models.CharField('Municipio',max_length=100,blank=False,null=False)
    altura = models.FloatField('Altura',blank=False,null=False)
    peso = models.FloatField('Peso', blank=False,null=False)
    
    class Meta:
            verbose_name = 'Paciente'
            verbose_name_plural = 'Pacientes'
            ordering = ['id_paciente']

    def __str__(self):
        return self.nombre + ' ' + self.apellidos

class Medico(models.Model):
    idMedico= models.AutoField('IdMedico',primary_key=True)
    nombre = models.CharField('Nombre',max_length=100, blank=False, null=False)
    apellidos = models.CharField('Apellidos', max_length=100, blank=False, null=False)
    dui = models.CharField('DUI', max_length=10, blank=False,null=False)
    sexo = models.CharField('Sexo', max_length=1, blank=False, null=False)
    email = models.CharField('email',max_length=100,blank=False, null=False)
    estadoCivil = models.CharField('estadoCivil', max_length=6, blank=False,null=False)
    telefono = models.IntegerField('Telefono', blank=False,null=False)
    fechaNaci = models.DateField('Fecha de Nacimiento',blank=False,null=False)
    direccion = models.TextField('Direccion',max_length=300, blank=False,null=False)
    departamento = models.CharField('Departamento',max_length=100,blank=False,null=False)
    municipio = models.CharField('Municipio',max_length=100,blank=False,null=False)
    altura = models.IntegerField('Altura',blank=False,null=False)
    peso = models.IntegerField('Peso', blank=False,null=False)

    class Meta:
        verbose_name='Medico'
        verbose_name_plural= 'Medicos'
        ordering=['idMedico']
    
    def __str__(self):
        return self.nombre + ' ' + self.apellidos

class Consulta (models.Model):
    idConsulta = models.AutoField(primary_key=True)
    idMedico = models.CharField('IdMedico', max_length=4, blank=False, null=False)
    idPaciente = models.CharField('IdPaciente', max_length=4, blank=False, null=False)
    idEspecialidad = models.CharField('IdEspecialidad', max_length=4, blank=False, null=False)
    idCita = models.CharField('IdCita',max_length=4,blank=False, null=False)
    fecha= models.DateField('FechaConsulta', blank=False, null=False)

    class Meta:
            verbose_name='Consulta'
            verbose_name_plural= 'Consultas'
            ordering=['idConsulta']
    
    def __str__(self):
        return self.idPaciente


class Referencia (models.Model):
    idReferencia = models.AutoField(primary_key =True)
    idMedico = models.CharField('IdMedico',max_length=4,blank=False,null=False)
    nombre= models.CharField('Nombre', max_length=50, blank=False, null=False)
    cargo = models.CharField('Cargo', max_length=50, blank=False, null=False)
    telefono = models.CharField('Telefono', max_length=50, blank=False, null=False)
    lugarReferencia = models.CharField('LugarReferencia', max_length=50,blank=False,null=False)
    tipoReferencia = models.CharField('TipoReferencia', max_length=50, blank=False, null=False)

    class Meta:
            verbose_name='Referencia'
            verbose_name_plural= 'Referencias'
            ordering=['idReferencia']
    
    def __str__(self):
        return self.nombre + ' ' + self.lugarReferencia

apps/clinica/forms.py
from django import forms
from .models import Paciente,Consulta

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['expediente','nombre','apellidos','dui','sexo','email','estadoCivil','telefono','fechaNaci', 'direccion', 'departamento','municipio','altura','peso']


class ConsultaForm(forms.ModelForm):
    class Meta:
        model = Consulta
        fields= ['idMedico','idPaciente','idEspecialidad','idCita','fecha']
    

apps/clinica/views.py
from django.shortcuts import render, redirect
from .models import Paciente, Consulta
from .forms import PacienteForm, ConsultaForm
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


def Home (request):
    return render(request,'index.html')


def crearPaciente(request):
    if request.method == 'POST':
        print(request.POST)
        paciente_form = PacienteForm(request.POST)
        if paciente_form.is_valid():
            paciente_form.save()
            return redirect('index.html')
    else :
        paciente_form = PacienteForm()
    return render(request,'clinica/crear_paciente.html',{'paciente_form':paciente_form})


def crearConsulta(request):
    if request.method == 'POST':
        print(request.POST)
        consulta_form = ConsultaForm(request.POST)
        if consulta_form.is_valid():
            consulta_form.save()
            return redirect('index')
    else :
        consulta_form = ConsultaForm()
    return render(request,'clinica/crear_consulta.html',{'consulta_form':consulta_form})


def listarPaciente(request):
    pacientes = Paciente.objects.all()
    return render(request, 'clinica/listar_paciente.html',{'pacientes':pacientes})

def editarPaciente(request,expediente):
    error = None
    try:
        paciente = Paciente.objects.get(expediente = expediente)
        if request.method == 'GET' :
            paciente_form = PacienteForm(instance = paciente)
        else:
            paciente_form = PacienteForm(request.POST, instance = paciente)
            if paciente_form.is_valid():
                paciente_form.save()
                return redirect('index')
    except ObjectDoesNotExist as e :
        error = e

    return render(request,'clinica/crear_paciente.html',{'paciente_form':paciente_form,'error':error})

templates/clinica/buscar_paciente.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}Pagina de Inicio de Sismedica{% endblock titulo %}</title>
    {% block extracss %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
    {% endblock extracss %}
</head>
<body>
    

    {% block header %}
    <header>
        <div class="contenedor">

            <div class="menu">
                <div class="Lmenu">
                    <nav class="navegacion">
                        <ul class="ulmenu">
                            <li><a href="index.html">Menu Principal</a></li>
                            <li><a href="#">Expediente</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_paciente' %}">Crear Paciente Nuevo</a> </li>
                                    <li><a href="#">Editar Paciente</a></li>
                                    <li><a href="#">Consultar Paciente</a></li>
                                </ul>
                            </li>    
                            <li><a href="#">Consulta</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_consulta' %}">Crear Consulta</a> </li>
                                    <li><a href="#">Gestionar Paciente</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Reportes</a></li>
                            <li><a href="#">Citas</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="sesion">
                    <img src="{% static 'img/imagen1.png' %}" alt="Mi imagen" width="75" height="100">
                    <ul>
                        <li>{{user.username | upper}}</li>
                        <li><button>editar perfil</button></li>
                        <li><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                    </ul>
                </div>
                
                
            </div>
        </div>

    </header>

    <body>
        
    </body>
    </html>

templates/clinica/crear_consulta.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingresar nueva Consulta</title>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos4.css' %}">
    <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script type="text/javascript" src="{% static 'js/formato.js' %}"> </script>
</head>
<body>

    

    <header>
        <div class="contenedor">

            <div class="menu">
                <div class="Lmenu">
                    <nav class="navegacion">
                        <ul class="ulmenu">
                            <li><a href="index.html">Menu Principal</a></li>
                            <li><a href="#">Expediente</a>
                                <ul class="submenu">
                                    <li><a href="#">Crear Paciente Nuevo</a> </li>
                                    <li><a href="#">Editar Paciente</a></li>
                                    <li><a href="#">Consultar Paciente</a></li>
                                </ul>
                            </li>    
                            <li><a href="#">Consulta</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_consulta' %}">Crear Consulta</a> </li>
                                    <li><a href="#">Gestionar Paciente</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Reportes</a></li>
                            <li><a href="#">Citas</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="sesion">
                    <img src="{% static 'img/imagen1.png' %}" alt="Mi imagen" width="75" height="100">
                    <ul>
                        <li>{{user.username | upper}}</li>
                        <li><button>editar perfil</button></li>
                        <li><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                    </ul>
                </div>
                
                
            </div>
        </div>
    </header>

<hr>

<h1>Ingresar Consulta</h1>

<body>
    
    <form method="POST" action="" class="con">
       <fieldset>
           <legend>Consulta</legend>
        {{consulta_form.as_p}}
        <button type="submit">Crear</button>
        <button type="reset">Borrar</button>
        </fieldset>
    </form>


</body>

    <footer>
        <h1><center>°SISMEDICA°</center></h1>
    </footer>
  

</body>
</html>

templates/clinica/crear_paciente.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingresar nuevo Paciente</title>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos5.css' %}">
    <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script type="text/javascript" src="{% static 'js/formato.js' %}"> </script>
</head>
<body>

    

    <header>
        <div class="contenedor">

            <div class="menu">
                <div class="Lmenu">
                    <nav class="navegacion">
                        <ul class="ulmenu">
                            <li><a href="index.html">Menu Principal</a></li>
                            <li><a href="#">Expediente</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_paciente' %}">Crear Paciente Nuevo</a> </li>
                                    <li><a href="#">Editar Paciente</a></li>
                                    <li><a href="#">Consultar Paciente</a></li>
                                </ul>
                            </li>    
                            <li><a href="#">Consulta</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_consulta' %}">Crear Consulta</a> </li>
                                    <li><a href="#">Gestionar Paciente</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Reportes</a></li>
                            <li><a href="#">Citas</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="sesion">
                    <img src="{% static 'img/imagen1.png' %}" alt="Mi imagen" width="75" height="100">
                    <ul>
                        <li>{{user.username | upper}}</li>
                        <li><button>editar perfil</button></li>
                        <li><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                    </ul>
                </div>
                
                
            </div>
        </div>
    </header>

    <hr>

    <h1 id="Ingreso">Ingresar los datos del Paciente</h1>
    <form action="" method="post">
        
        {% csrf_token %}   
        
            <p><label for="id_expediente">No.Expediente:</label></p> 
                <input type="number" name="expediente" required="" id="id_expediente"><br/>
            <p><label for="id_nombre">Nombre:</label></p>
                 <input type="text" name="nombre" maxlength="100" required="" id="id_nombre"><br/>
            <p><label for="id_apellidos">Apellidos:</label></p> 
                <input type="text" name="apellidos" maxlength="100" required="" id="id_apellidos"><br/>
            <p><label for="id_dui">DUI:</label></p>
                 <input type="text" name="dui" maxlength="10" required="" id="id_dui"><br/>
            <p><label for="id_sexo">Sexo:</label></p> 
                <input type="text" name="sexo" maxlength="1" required="" id="id_sexo"><br/>
            <p><label for="id_email">Email:</label></p> 
                <input type="text" name="email" maxlength="100" required="" id="id_email"><br/>
            <p><label for="id_estadoCivil">EstadoCivil:</label></p> 
                <input type="text" name="estadoCivil" maxlength="10" required="" id="id_estadoCivil"><br/>
            <p><label for="id_telefono">Telefono:</label></p>
                <input type="text" name="telefono" required="" id="id_telefono"><br/><br/>
            <p><label for="id_fechaNaci">Fecha de Nacimiento:</label></p>
                <input type="date" name="fechaNaci" required="" id="id_fechaNaci"><br/>
            <p><label for="id_direccion">Direccion:</label></p> 
                <textarea name="direccion" cols="40" rows="10" maxlength="300" required="" id="id_direccion"></textarea><br/>
            <p><label for="id_departamento">Departamento:</label></p>
                <input type="text" name="departamento" maxlength="100" required="" id="id_departamento"></br>
            <p><label for="id_municipio">Municipio:</label></p> 
                <input type="text" name="municipio" maxlength="100" required="" id="id_municipio"><br/>
            <p><label for="id_altura">Altura:</label></p>
                <input type="number" name="altura" required="" id="id_altura"><br/>
            <p><label for="id_peso">Peso:</label></p> 
                <input type="number" name="peso" required="" id="id_peso"><br/>
        <br>
        <button type="submit" onclick="HizoClic()">Crear</button>
        <button type="reset">Limpiar Datos</button>
    </form>

    <footer>
        <h1><center>°SISMEDICA°</center></h1>
    </footer>
  

</body>
</html>

templates/clinica/listar_paciente.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}Pagina de Inicio de Sismedica{% endblock titulo %}</title>
    {% block extracss %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
    {% endblock extracss %}
</head>
<body>
    

 
    <header>
        <div class="contenedor">

            <div class="menu">
                <div class="Lmenu">
                    <nav class="navegacion">
                        <ul class="ulmenu">
                            <li><a href="index.html">Menu Principal</a></li>
                            <li><a href="#">Expediente</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_paciente' %}">Crear Paciente Nuevo</a> </li>
                                    <li><a href="#">Editar Paciente</a></li>
                                    <li><a href="#">Consultar Paciente</a></li>
                                </ul>
                            </li>    
                            <li><a href="#">Consulta</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_consulta' %}">Crear Consulta</a> </li>
                                    <li><a href="#">Gestionar Paciente</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Reportes</a></li>
                            <li><a href="#">Citas</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="sesion">
                    <img src="{% static 'img/imagen1.png' %}" alt="Mi imagen" width="75" height="100">
                    <ul>
                        <li>{{user.username | upper}}</li>
                        <li><button>editar perfil</button></li>
                        <li><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                    </ul>
                </div>
                
                
            </div>
        </div>

    </header>


    {% if pacientes %}
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tbody>
        {% for paciente in pacientes %}
        <tr>
          <td>{{paciente.expediente}}</td>
          <td>{{paciente.nombre}}</td>
          <td>{{paciente.apellidos}}</td>
          <td>
            <a href="{% url 'clinica:editar_paciente' paciente.expediente %}">Actualizar</a>
          </td>
          <td>
            <a href="#">Eliminar</a>
          </td>
        </tr>
  
        {% endfor %}
      </tbody>
    </table>

    {% else %}
    <h1>No existen autores registrados</h1>
  {% endif %}
</body>
</html> 

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}Pagina de Inicio de Sismedica{% endblock titulo %}</title>
    {% block extracss %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
    {% endblock extracss %}
</head>
<body>
    

    {% block header %}
    <header>
        <div class="contenedor">

            <div class="menu">
                <div class="Lmenu">
                    <nav class="navegacion">
                        <ul class="ulmenu">
                            <li><a href="index.html">Menu Principal</a></li>
                            <li><a href="#">Expediente</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'clinica:crear_paciente' %}">Crear Paciente Nuevo</a> </li>
                                    <li><a href="#">Editar Paciente</a></li>
                                    <li><a href="#">Consultar Paciente</a></li>
                                </ul>
                            </li>    
                            <li><a href="#">Consulta</a>
                                <ul class="submenu">
                                    <li><a href="#">Crear Consulta</a> </li>
                                    <li><a href="#">Gestionar Paciente</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Reportes</a></li>
                            <li><a href="#">Citas</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="sesion">
                    <img src="{% static 'img/imagen1.png' %}" alt="Mi imagen" width="75" height="100">
                    <ul>
                        <li>{{user.username | upper}}</li>
                        <li><button>editar perfil</button></li>
                        <li><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                    </ul>
                </div>
                
                
            </div>
        </div>

    </header>

    {% endblock header %}
    <hr>
    {% block content %}
    <section id="Mision">
        <div class="contenedor">
            <div class="texto">
                <h1><b>Misión</b></h1>
                <p><h4>Somos la instancia del Estado rectora en materia de salud, que garantiza a los habitantes de la República de El Salvador la cobertura de servicios oportunos e integrales, con equidad, calidad y calidez, en corresponsabilidad con la comunidad, incluyendo todos los sectores y actores sociales, para contribuir a lograr una mejor calidad de vida.</h4></p>
            </div>
            <div class="imagen">
                <img src="{% static 'img/imagen2.jpg' %}" alt="">
            </div>
        </div>
    </section>
    <hr>

    <section id="vision">
        <div class="contenedor">
            <div class="imagen">
                <img src="{% static 'img/imagen3.jpg' %}" alt="">
            </div>
            <div class="texto">
            <h1><b>Visión</b></h1>
            <p><h4>Instancia rectora del sector fortalecida, 
                conduciendo de manera eficiente y efectiva el 
                Sistema Nacional de Salud y garantizando a los habitantes de la República de El Salvador 
                servicios integrales de salud en armonía con el 
                ambiente, con equidad, calidad y calidez,
                 para la conservación y restablecimiento de la salud,
                 estimulando para ello la corresponsabilidad y la contraloría social.</h4></p>
            </div>
        </div>
    </section>
    {% endblock content %}
<hr>

{% block footer %}
    <footer id="final">
        <div id="redes">
            <ul>
                <li><img src="{% static 'img/fb.png' %}" alt="" width="50" height="75"></li>
                <li><img src="{% static 'img/ig.png' %}" alt="" width="50" height="75"></li>
                <li><img src="{% static 'img/twitter.png' %}" alt="" width="50" height="75"></li>
                <li><img src="{% static 'img/wa.png' %}" alt="" width="50" height="75"></li>
            </ul>
        </div>
        <p><h2><b><center>Contactanos al : 2214-8697</center></b></h2></p>
    </footer>
{% endblock footer %}


</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de Sesion</title>
    <link rel="stylesheet" href="{% static 'css/estilos2.css' %}">
</head>
<body>

    <form id="entrada" method="post">
        {% csrf_token %}
        <div class="decoracion">
            <center><img src="{% static 'img/doctorlogin.png' %}" alt="" height="100"></center>
        </div>
        <div class="arrow">
            <div class="col-md-6 col-md-offset-3">
                <label for="username">Nombre de usuario:</label>
                <input type="text" class="form-control" name="username">
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="form-group">
                    <label for="username">Contraseña</label>
                    <input type="password" class="form-control" name="password">
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="form-group">
                    <label for="username">Olvidé mi contraseña</label>
                    <input class="btn btn-primary" type="submit" value="Ingresar">
                </div>
            </div>
        </div>
    </form>
    
</body>
</html>